# Generated by Django 3.0.8 on 2020-07-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200725_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='poster',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='product_images/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='product_images/', verbose_name='Главное фото'),
        ),
    ]
